image: docker:latest
services:
    - docker:dind

stages:
    - build
    - test
    - deploy

before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose push

deploy:
    stage: deploy
    only:
        - master
    before_script:
        - apk add --no-cache openssh-client py-pip py-crypto bash rsync gcc musl-dev linux-headers python-dev make libffi-dev libxml2-dev openssl-dev libgit2-dev python3-dev
        - pip install fabric
        - eval $(ssh-agent -s)
        - bash -c 'ssh-add <(echo "$DEPLOY_KEY")'
        - mkdir -p ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    script:
        - fab -H $DEPLOY_ADDR deploy