version: '2'
services:
    backend:
        image: registry.gitlab.com/de1ay/enterprice-model-panel:latest
        build: ./backend
        environment:
            - SECRET_KEY=${SECRET_KEY}
        command: bash -c "sleep 5 && python ./manage.py makemigrations && python ./manage.py migrate --run-syncdb && uwsgi /usr/src/app/uwsgi.ini"
        volumes:
            - ./static:/usr/src/app/static
        restart: unless-stopped

    test:
        image: registry.gitlab.com/de1ay/enterprice-model-panel:latest
        build: ./backend
        command: python manage.py test
        depends_on:
            - postgres
        links:
            - postgres
        restart: "no"

    postgres:
        image: postgres:latest
        environment:
            - PGDATA=/tmp
            - POSTGRES_USER=root
            - POSTGRES_DB=entmode
            - POSTGRES_PASSWORD=2929dfd581e1d7d4f89d8131521e4173ccbc0e2ea9be11756cc6693bbd3cf893
        ports:
            - "5432:5432"
        volumes:
            - ../postgres:/var/lib/postgresql/data
        restart: unless-stopped

    nginx:
        image: nginx:mainline
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx:ro
            - ./static:/usr/src/app/static
            - ./frontend/dist:/usr/src/app/frontend
        depends_on:
            - backend
        restart: unless-stopped