# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_brand', models.CharField(max_length=64)),
                ('deal_sum', models.FloatField()),
                ('deal_type', models.CharField(max_length=1)),
                ('deal_time', models.FloatField()),
                ('deal_period', models.TextField()),
                ('deal_paid', models.FloatField()),
                ('deal_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
