# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
        ),
    ]
