# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_deal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='deal_type',
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_paid',
            field=models.FloatField(default=0),
        ),
    ]
