# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_auto_20171028_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
