# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0004_auto_20171028_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_sum', models.IntegerField()),
                ('billing_date', models.CharField(max_length=10)),
                ('billing_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Deal')),
            ],
        ),
    ]
