# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=64)),
                ('media_type', models.CharField(max_length=1)),
                ('media_address', models.CharField(max_length=128)),
            ],
        ),
    ]
