# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_address',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
